import { Provider } from "@/components/ui/provider";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
	subsets: ["latin"],
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={outfit.className}>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
